[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200
via_ir = false

[rpc_endpoints]
mantle_testnet = "https://rpc.testnet.mantle.xyz"
mantle_mainnet = "https://rpc.mantle.xyz"

[etherscan]
mantle_testnet = { key = "${API_KEY_BLOCKSCOUT}", url = "https://explorer.testnet.mantle.xyz/api" }
mantle_mainnet = { key = "${API_KEY_BLOCKSCOUT}", url = "https://explorer.mantle.xyz/api" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config